In [1]:
import pandas as pd
import numpy as np

path = r"C:\Users\ps302\OneDrive\Desktop\Hydrology\src\Flood_Model\data\raw\mahanadi_10k_2.csv"
df = pd.read_csv(path)
df.head()

,easting,northing,point_id,distance_to_river,aspect,dem,flow_accumulation,twi,slope,flood,rainfall,drainage_density,ext_rainfall,lulc,soil
0,133952.230146,2.249638e+06,0,10993.2705,177.989240,183.269820,18,10.043777,1.200029e+00,0,1714.680084,0.008238,30.779120,40,29
1,206784.841335,2.468185e+06,1,8457.0740,317.784550,282.669430,1,8.483146,2.028161e+00,0,1561.825018,0.006385,34.464436,40,30
2,459671.933327,2.241227e+06,2,3313.8800,57.226437,0.000346,6,12.700654,9.576796e-07,0,1767.091847,0.045409,36.737860,80,36
3,44328.737440,2.570529e+06,3,9742.9820,152.312100,538.788700,2,9.058740,4.337976e+00,0,1424.827479,0.024082,32.841915,10,31
4,60077.196604,2.480489e+06,4,2313.1147,43.902390,298.437530,2,8.486233,7.265088e-01,0,1839.188680,0.027140,32.228870,50,31

In [2]:
df.columns

Index(['easting', 'northing', 'point_id', 'distance_to_river', 'aspect', 'dem',
       'flow_accumulation', 'twi', 'slope', 'flood', 'rainfall',
       'drainage_density', 'ext_rainfall', 'lulc', 'soil'],
      dtype='object')

In [21]:
print(df["easting"].min(), df["easting"].max())
print(df["northing"].min(), df["northing"].max())

-183979.43397059967 472193.4738343004
2145489.077111672 2611878.1966391425

In [22]:
print(df[['easting', 'northing']].head())

         easting      northing
0  133952.230146  2.249638e+06
1  206784.841335  2.468185e+06
2  459671.933327  2.241227e+06
3   44328.737440  2.570529e+06
4   60077.196604  2.480489e+06

In [23]:
df.columns

Index(['easting', 'northing', 'point_id', 'distance_to_river', 'aspect', 'dem',
       'flow_accumulation', 'twi', 'slope', 'flood', 'rainfall',
       'drainage_density', 'ext_rainfall', 'lulc', 'soil'],
      dtype='object')

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9755 entries, 0 to 9754
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   easting            9755 non-null   float64
 1   northing           9755 non-null   float64
 2   point_id           9755 non-null   int64
 3   distance_to_river  9755 non-null   float64
 4   aspect             9755 non-null   float64
 5   dem                9755 non-null   float64
 6   flow_accumulation  9755 non-null   int64
 7   twi                9755 non-null   float64
 8   slope              9755 non-null   float64
 9   flood              9755 non-null   int64
 10  rainfall           9755 non-null   float64
 11  drainage_density   9755 non-null   float64
 12  ext_rainfall       9755 non-null   float64
 13  lulc               9755 non-null   int64
 14  soil               9755 non-null   int64
dtypes: float64(10), int64(5)
memory usage: 1.1 MB

In [25]:
df["flood"].value_counts()

flood
0    9286
1     469
Name: count, dtype: int64

In [26]:
df.isna().sum()

easting              0
northing             0
point_id             0
distance_to_river    0
aspect               0
dem                  0
flow_accumulation    0
twi                  0
slope                0
flood                0
rainfall             0
drainage_density     0
ext_rainfall         0
lulc                 0
soil                 0
dtype: int64

In [27]:
# df["soil"].value_counts()
df["slope"].value_counts()

slope
0.000000e+00    78
1.018184e-06     8
9.680285e-07     6
1.020171e-06     6
9.940344e-07     4
                ..
2.067922e+00     1
9.561495e-07     1
2.051646e+00     1
6.789571e-01     1
2.021835e+00     1
Name: count, Length: 9644, dtype: int64

In [29]:
df.corr()

,easting,northing,point_id,distance_to_river,aspect,dem,flow_accumulation,twi,slope,flood,rainfall,drainage_density,ext_rainfall,lulc,soil
easting,1.000000,-0.309986,-0.000503,-0.140259,-0.018852,-0.432336,0.036191,0.010384,0.088815,0.175823,-0.221608,0.015067,0.282150,-0.056281,-0.353752
northing,-0.309986,1.000000,0.013104,-0.108848,0.053393,0.319625,-0.015319,-0.044164,-0.046507,-0.118675,0.078959,-0.003361,0.232050,0.026227,0.250606
point_id,-0.000503,0.013104,1.000000,-0.013717,-0.001243,0.012550,-0.011428,-0.014127,0.024025,0.015430,0.000491,-0.003828,0.010147,-0.009173,-0.006582
distance_to_river,-0.140259,-0.108848,-0.013717,1.000000,0.014302,0.124663,-0.050513,-0.045661,0.006249,-0.111349,-0.005070,-0.020455,-0.066029,-0.078205,0.073267
aspect,-0.018852,0.053393,-0.001243,0.014302,1.000000,0.103375,-0.023265,-0.228295,0.101762,-0.159144,-0.039320,-0.078968,0.003267,-0.163748,0.141115
dem,-0.432336,0.319625,0.012550,0.124663,0.103375,1.000000,-0.049394,-0.393312,0.427499,-0.224229,-0.114383,-0.074729,-0.165220,-0.320248,0.302886
flow_accumulation,0.036191,-0.015319,-0.011428,-0.050513,-0.023265,-0.049394,1.000000,0.072790,-0.011306,0.121797,-0.005493,0.141866,0.002002,0.087066,-0.181568
twi,0.010384,-0.044164,-0.014127,-0.045661,-0.228295,-0.393312,0.072790,1.000000,-0.539612,0.257208,0.074599,0.585907,-0.005113,0.448781,-0.158776
slope,0.088815,-0.046507,0.024025,0.006249,0.101762,0.427499,-0.011306,-0.539612,1.000000,-0.117979,-0.016824,-0.084892,-0.051827,-0.460924,0.061735
flood,0.175823,-0.118675,0.015430,-0.111349,-0.159144,-0.224229,0.121797,0.257208,-0.117979,1.000000,0.032708,0.150493,0.029517,0.426590,-0.498506
rainfall,-0.221608,0.078959,0.000491,-0.005070,-0.039320,-0.114383,-0.005493,0.074599,-0.016824,0.032708,1.000000,-0.004177,-0.137944,0.094813,0.177080
drainage_density,0.015067,-0.003361,-0.003828,-0.020455,-0.078968,-0.074729,0.141866,0.585907,-0.084892,0.150493,-0.004177,1.000000,-0.027916,0.123673,-0.081100
ext_rainfall,0.282150,0.232050,0.010147,-0.066029,0.003267,-0.165220,0.002002,-0.005113,-0.051827,0.029517,-0.137944,-0.027916,1.000000,-0.050020,-0.141229
lulc,-0.056281,0.026227,-0.009173,-0.078205,-0.163748,-0.320248,0.087066,0.448781,-0.460924,0.426590,0.094813,0.123673,-0.050020,1.000000,-0.251433
soil,-0.353752,0.250606,-0.006582,0.073267,0.141115,0.302886,-0.181568,-0.158776,0.061735,-0.498506,0.177080,-0.081100,-0.141229,-0.251433,1.000000

In [35]:
df["lulc"].value_counts()

lulc
40    4366
10    3727
30    1148
80     245
50     129
60      81
20      48
90      10
95       1
Name: count, dtype: int64

### Why Convert LULC to Category Type
- Treats `lulc` as a nominal categorical variable, not as a continuous numeric value.
- Prevents misleading ordinal interpretation of land cover labels.
- Reduces memory usage compared to plain object/string storage.
- Keeps preprocessing simple and consistent before model-specific encoding.
- Allows flexible downstream handling: native categorical support (if available) or later encoding only when required.

###### One-hot encoding provides explicit separation of categories, while categorical encoding allows tree-based models to internally learn optimal splits without increasing feature dimensions

In [3]:
df["lulc"] = df["lulc"].astype("category")

In [4]:
df.head()

,easting,northing,point_id,distance_to_river,aspect,dem,flow_accumulation,twi,slope,flood,rainfall,drainage_density,ext_rainfall,lulc,soil
0,133952.230146,2.249638e+06,0,10993.2705,177.989240,183.269820,18,10.043777,1.200029e+00,0,1714.680084,0.008238,30.779120,40,29
1,206784.841335,2.468185e+06,1,8457.0740,317.784550,282.669430,1,8.483146,2.028161e+00,0,1561.825018,0.006385,34.464436,40,30
2,459671.933327,2.241227e+06,2,3313.8800,57.226437,0.000346,6,12.700654,9.576796e-07,0,1767.091847,0.045409,36.737860,80,36
3,44328.737440,2.570529e+06,3,9742.9820,152.312100,538.788700,2,9.058740,4.337976e+00,0,1424.827479,0.024082,32.841915,10,31
4,60077.196604,2.480489e+06,4,2313.1147,43.902390,298.437530,2,8.486233,7.265088e-01,0,1839.188680,0.027140,32.228870,50,31

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9755 entries, 0 to 9754
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   easting            9755 non-null   float64
 1   northing           9755 non-null   float64
 2   point_id           9755 non-null   int64
 3   distance_to_river  9755 non-null   float64
 4   aspect             9755 non-null   float64
 5   dem                9755 non-null   float64
 6   flow_accumulation  9755 non-null   int64
 7   twi                9755 non-null   float64
 8   slope              9755 non-null   float64
 9   flood              9755 non-null   int64
 10  rainfall           9755 non-null   float64
 11  drainage_density   9755 non-null   float64
 12  ext_rainfall       9755 non-null   float64
 13  lulc               9755 non-null   category
 14  soil               9755 non-null   int64
dtypes: category(1), float64(10), int64(4)
memory usage: 1.1 MB

In [5]:
import os
path_processed = r"C:\Users\ps302\OneDrive\Desktop\Hydrology\src\Flood_Model\data\proceessed"
output_path = os.path.join(path_processed, "flood_training_data_10k_clean.csv")
df.to_csv(output_path, index=False)
print(f"Saved: {output_path}")

Saved: C:\Users\ps302\OneDrive\Desktop\Hydrology\src\Flood_Model\data\proceessed\flood_training_data_10k_clean.csv